// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJRWMlrJfIag18c6cWBMmSM3se2rzArL4',
    appId: '1:844647056548:web:f4b3f540e0318b80d29231',
    messagingSenderId: '844647056548',
    projectId: 'mood-3a15b',
    authDomain: 'mood-3a15b.firebaseapp.com',
    storageBucket: 'mood-3a15b.firebasestorage.app',
    measurementId: 'G-G37XVYHH8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBubvmPa3PvgIbEGKTF_zLevCb-Mdz_Q9s',
    appId: '1:844647056548:android:f58c2fac7475fe6dd29231',
    messagingSenderId: '844647056548',
    projectId: 'mood-3a15b',
    storageBucket: 'mood-3a15b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxrXrIlY1y4pnSpV72ZcpWMYTbbcdV5Jo',
    appId: '1:844647056548:ios:d505e85e06c7d1e4d29231',
    messagingSenderId: '844647056548',
    projectId: 'mood-3a15b',
    storageBucket: 'mood-3a15b.firebasestorage.app',
    iosBundleId: 'com.example.moodCat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxrXrIlY1y4pnSpV72ZcpWMYTbbcdV5Jo',
    appId: '1:844647056548:ios:d505e85e06c7d1e4d29231',
    messagingSenderId: '844647056548',
    projectId: 'mood-3a15b',
    storageBucket: 'mood-3a15b.firebasestorage.app',
    iosBundleId: 'com.example.moodCat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJRWMlrJfIag18c6cWBMmSM3se2rzArL4',
    appId: '1:844647056548:web:b0e0885f6e57fbdcd29231',
    messagingSenderId: '844647056548',
    projectId: 'mood-3a15b',
    authDomain: 'mood-3a15b.firebaseapp.com',
    storageBucket: 'mood-3a15b.firebasestorage.app',
    measurementId: 'G-5F15LC88DE',
  );
}
